name: Release Automation Action
author: SeungBin Kim
description: Automates the release process using semantic versioning and GitHub Actions.
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
