name: Tag and Release
on:
  issues:
    types: [ opened, unlabeled ]
  pull_request:
    types: [ opened, unlabeled ]
jobs:
  permissions:
    issues: write
    pull-requests: write
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Local Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
