name: Tag and Release
on:
  issues:
    types: [ opened, unlabeled ]
  pull_request:
    types: [ opened, unlabeled ]
permissions:
  issues: write
  pull-requests: write
jobs:
  label-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.label-check.outputs.status }}
      error: ${{ steps.label-check.outputs.error }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run package
      - name: Test Local Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
